routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

// Route::get('/', function () {
//     return view('welcome');
// })->name('welcome');

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');
Route::get('/', 'HomeController@welcome')->name('welcome');

// start role routes
Route::resource('/roles','RoleController');
Route::view('/rules','rules')->name('rules');
// end role routes

// start user routes
Route::get('/users/stop','UserController@origUser')->name('users.orig');
Route::get('/users/stats','UserController@stats')->name('users.stats');
Route::get('/users/list','UserController@list')->name('users.list');
Route::resource('/users','UserController',['except'=>['create']]);

Route::group(['prefix'=>'users/{user}/', 'as'=>'users.'], function() {
	Route::get('verify/{email_key}', 'Auth\RegisterController@verifyUser')->name('verify');
	Route::resource('points','PointController', ['only'=>['index']]);
	Route::group(['prefix'=>'points', 'as'=>'points.'], function(){
		Route::get('buy','PointController@buyForm')->name('buy.form');
		Route::post('buy','PointController@buyStore')->name('buy');
	});
});

Route::group(['prefix'=>'points','as'=>'points.'], function() {
	Route::get('bulkAdd','PointController@bulkAdd')->name('bulkAdd');
	Route::post('bulkAdd','PointController@bulkStore')->name('bulkStore');
});

// end user routes

// switch user
Route::get('/users/{user}/switch','UserController@switchUser')->name('users.switch')->middleware('can:switchUser,App\User');
// end switch user

Route::post('/invitations/{invitation}/resend', 'InvitationController@resend')->name('invitations.resend');
Route::resource('/invitations','InvitationController');

Route::get('/teams/list', 'TeamController@list')->name('teams.list');
Route::resource('/teams', 'TeamController');
Route::resource('/games', 'GameController');
Route::get('/games/generate/{group}', 'GameController@generate')->name('games.generate');

Route::group(['prefix'=>'games/{game}', 'as'=>'games.'], function() {
	Route::resource('predictions', 'PredictionController');	
	Route::get('result', 'GameController@getResults')->name('result');	
	Route::put('result', 'GameController@saveResults')->name('result.save');	
});

Route::get('leaderboard','RankController@leaderboard')->name('leaderboard');

Route::get('/users/{user}/deleteAvatar', 'UserController@deleteAvatar')->name('users.deleteAvatar');

Route::resource('/feedback','FeedbackController',['only'=>['store','index']]);

app/User.php
<?php

namespace App;

use Illuminate\Notifications\Notifiable;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Mail;
use DB;
use Cache;

use App\Http\Controllers\RankController;

class User extends Authenticatable
{
    use Notifiable;

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token', 'email_key', 'suspended', 'api_token'
    ];

    protected $fillable = [
        'email', 'name',  'password', 'email_key', 'mobile', 'gender', 'avatar'
    ];

    protected $casts = [
        'suspended' => 'boolean',
    ];

    protected $appends = ['prediction_form', 'avatar'];

    public function makeExchange(Exchange $exchange)
    {
        return $this->exchanges()->save($exchange);
    }

    public function exchanges()
    {
        return $this->hasMany(Exchange::class);
    }

    public function avatar()
    {
        return $this->avatar?\Storage::url($this->avatar):asset('avatar.jpg');
    }

    public function getAvatarAttribute()
    {
        return !blank($this->attributes['avatar']) ? \Storage::url($this->attributes['avatar']):asset('avatar.jpg');
    }
    
    public function predictions()
    {
        return $this->hasMany(Prediction::class);
    }

    public function getNameAttribute()
    {
        return title_case($this->attributes['name']);
    }

    public function setNameAttribute($value)
    {
        $this->attributes['name'] = title_case($value);
    }

    public function setEmailKeyAttribute($value)
    {
        $this->attributes['email_key'] = $value ? encrypt($value) : null;
    }

    public function getEmailKeyAttribute()
    {
        return $this->attributes['email_key'] ? decrypt($this->attributes['email_key']) : null;
    }
    public function setEmailAttribute($value)
    {
        return $this->attributes['email'] = strtolower($value);
    }

    public function getVerifiedAttribute()
    {
        return blank($this->email_key);
    }

    public function scopeVerified($query)
    {
        return $query->whereNull('email_key');
    }

    public function scopePending($query)
    {
        return $query->whereNotNull('email_key');
    }

    public function scopeSuspended($query)
    {
        return $query->whereSuspended(true);
    }
    
    public function scopeActive($query)
    {
        return $query->whereSuspended(false);
    }

    public function owns($relation)
    {
        return $relation->user_id === $this->id ;
    }

    public function isSelf()
    {
        return $this->id === auth()->user()->id;
    }

    public function isOwnRequest()
    {
        return $this->id === request()->user->id;
    }

    public function verify()
    {
        DB::transaction(function() {
            $this->email_key = null;
            $this->save();
        });
    }


    public function isSuperAdmin() 
    {
        return $this->id===1?:false;
    }

    public function roles()
    {
        return $this->belongsToMany(Role::class);
    }

    public function points()
    {
        return $this->hasMany(Point::Class);
    }

    public function addPoints(Point $point)
    {
        $point->multiplier = 1;
        $point->points = ceil($point->points);
        return $this->points()->save($point);
    }

    public function deductPoints(Point $point)
    {
        $point->multiplier = -1;
        $point->points = ceil($point->points);
        return $this->points()->save($point);
    }

    public function assignRole($role)
    {
        return $this->roles()->sync($role);
    }
    
    public function assignRoleById($role)
    {
        return $this->assignRole(Role::find($role));
    }

    public function hasRole($role)
    {
        if($this->isSuperAdmin())
            return true;

        if(is_string($role)) {
            return $this->roles->contains('name',$role);
        }

        return !! $role->intersect($this->roles)->count();
    }

    public function getWalletPointsAttribute()
    {
        return $this->points->sum(function($points) { return $points['multiplier'] * $points['points']; });
    }

    public function getPointsInPredictionAttribute()
    {
        return $this->total_points - $this->wallet_points;
    }

    public function getTotalPointsAttribute()
    {
        $points_for_all = RankController::getTotalPointsForRanking();
        $user_total_points = collect($points_for_all)->where('user_id',$this->id)->pluck('total_points')->first();
        return $user_total_points;
    }

    public function getPastPredictionsAttribute()
    {
        return DB::select(DB::raw(__("
            select count(*) num_predictions
                from predictions p
                    , games g
                where p.user_id=:user_id
                    and g.id=p.game_id
                    and g.scheduled_at < now();
        ",['user_id'=>$this->id])))[0]->num_predictions;
    }

    public function getPastTimePredictionsAttribute()
    {
        return DB::select(DB::raw(__("
            select count(*) num_predictions
                from predictions p
                    , games g
                where p.user_id=:user_id
                    and g.id=p.game_id
                    and g.scheduled_at < now()
                    and p.time is not null;
        ",['user_id'=>$this->id])))[0]->num_predictions;
    }

    public function getPredictionFormAttribute()
    {
        return Cache::rememberForever('user-prediction_form_'.$this->id, function() {
            if(!($this->past_predictions + $this->past_time_predictions))
                return 0;
            return round(($this->earned_wins / ($this->past_predictions + $this->past_time_predictions)) * 100);
        });
    }

    public function getAverageLossAttribute()
    {
        return $this->points()->debit()->get()->avg('points');
    }
    
    public function getAverageGainAttribute()
    {
        return $this->points()->credit()->get()->avg('points');
    }

    public function getTotalLossAttribute()
    {
        return $this->points()->debit()->get()->sum('points');
    }
    
    public function getTotalGainAttribute()
    {
        return $this->points()->credit()->get()->sum('points');
    }

    public function getRankAttribute()
    {
        $ranks = RankController::generate();
        return $ranks->where('user.id', $this->id)->first()['rank'] ? 
                : collect($ranks->get('others'))->where('user.id',$this->id)->first()['rank'];
    }

    public function getEarnedWinsAttribute()
    {
        return $this->predictions->sum('wins');
    }

    public function getWinsExchangedAttribute()
    {
        return $this->exchanges->sum('wins_sold');
    }

    public function getTotalWinsAttribute()
    {
        return $this->earned_wins - $this->wins_exchanged;
    }

    public function getPredictionFor(Game $game)
    {
        return $this->predictions()->game($game);
    }

    public function hasPredicted(Game $game)
    {
        return $this->getPredictionFor($game)->count();
    }

}

app/Http/Controllers/UserController.php
<?php

namespace App\Http\Controllers;

use App\User;
use App\Role;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Hash;
use Illuminate\Support\Facades\Log;

use Intervention\Image\ImageManagerStatic as Image;


use Illuminate\Http\File;

use Storage;

use DB;
use Sms;

class UserController extends Controller
{

    public function __construct()
    {
        $this->middleware('auth');
    }

    public function notifications(User $user)
    {
        $user->unreadNotifications->markAsRead();
        return redirect()->back();
    }

    public function list()
    {
        $users = User::where('name','like','%'.strtolower(request('term')).'%')->orWhere('email',request('term'))->get();
        $roles = Role::withCount('users')->where('name','like','%'.strtolower(request('term')).'%')->orWhere('label',request('term'))->get();

        $results=array();

        foreach($users as $user)
            $results[] = array(
                                'label'=>'User: '.$user->name.' ('.$user->email.')'
                                , 'value'=>$user->email
                                , 'avatar' => $user->avatar
                                , 'user_id' => $user->id
                                , 'type' => 'User'
                            );

        foreach($roles as $role)
            $results[] = array(
                                'label'=>'Role: '.$role->label.' ('.$role->name.' / '.($role->users_count+1).' '.str_plural('user',$role->users_count+1).')'
                                , 'value'=>$role->name
                                , 'role_name'=>$role->name
                                , 'type' => 'Role'
                                , 'avatar' => '//www.gravatar.com/avatar/'.md5("no-reply@fifa.glibix.com").'.png?s=140'
                            );

        return $results;
    }

    public function stats(User $user)
    {
        $this->authorize(User::class);

        return view('users.stats');
    }

    public function switchUser(User $user)
    {
        $this->authorize($user);
        $action_by = auth()->user()->email;
        session()->put('orig_user',auth()->user());
        auth()->login($user);
        Log::info("Switched to different user",['user'=>$user->email, 'action_by'=>$action_by, 'session'=>session()->getId()]);
        return redirect()->route('home');
    }

    public function origUser(User $user)
    {
        $old_user = auth()->user()->email;
        auth()->login(session()->pull('orig_user'));
        Log::info('User switched back',['from_user'=>$old_user]);
        return redirect()->back();
    }

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index(User $user)
    {
        $this->authorize(auth()->user());

        $users=$user->orderBy('name')->paginate(config('app.page_size'));

        return view('users.index',compact('users'));
    }

    public function show(User $user)
    {
        $this->authorize('view',$user);
        return view('users.show',compact('user'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\User  $user
     * @return \Illuminate\Http\Response
     */
    public function edit(User $user)
    {
        $this->authorize('update',$user);

        return view('users.edit',compact('user'));
    }

    public function verifyUser($attribute, $value, $parameters, $validator)
    {
        return Hash::check($value, auth()->user()->password);
    }

    public function hasRole($attribute, $value, $parameters, $validator)
    {
        return auth()->user()->hasRole($parameters[0]);
    }

    public function deleteAvatar(User $user)
    {
        $this->authorize('update', $user);
        if(Storage::disk("public")->exists($user->avatar))
            Storage::disk("public")->delete($user->avatar);
        $user->avatar=NULL;
        $user->save();
        return redirect()->back();
    }

    private function resizeAvatar($image_file)
    {
        $resized = Image::make($image_file);
        $resized->resize(140,140);
        $resized->save($image_file);
    }

    private function saveAvatar(User $user, $avatar)
    {
        $file_temp_path = Storage::path("tmp.avatar.".uniqid().'.jpg');

        file_put_contents($file_temp_path, base64_decode(preg_replace('#^data:image/\w+;base64,#i', '', $avatar)));

        $this->resizeAvatar($file_temp_path);

        $file_save_path = Storage::disk("public")->putFile("avatars", new File($file_temp_path));

        unlink($file_temp_path);

        if($user->avatar)
            $this->deleteAvatar($user);

        return $file_save_path;
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\User  $user
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, User $user)
    {
        $this->authorize($user);

        $conditions = collect([ 'password'=>'nullable|string|min:6|confirmed'
                                , 'name'=>'required|string'
                                , 'current_password'=>'required|verify_user'
                                , 'suspended'=>'sometimes|has_role:user_suspend'
                            ]);


        $this->validate($request, $conditions->all());

        DB::transaction(function() use($request, $user){

            if($request->filled("avatar-data"))
                $user->avatar = $this->saveAvatar($user, $request->input("avatar-data"));

            if($request->filled('password'))
            {
                $user->password = Hash::make(request('password'));
                $user->api_token = str_random(60);
            }

            if($request->has('suspended'))
                if($user->isSelf() || $user->isSuperAdmin())
                    abort(403,'Unauthorized access');

            if(auth()->user()->can('user_update_role') && !$user->isSelf())
                $user->assignRole($request->role);
            
            $user->name = $request->name;

            Log::debug('User profile update',['old'=>$user->mobile,'new'=>$request->mobile]);

            if(Auth()->user()->hasRole('user_suspend'))
                $user->suspended = $request->suspended?:false;
            
            if(Auth()->user()->hasRole('user_verify') && $request->filled('verified'))
                $user->verify();

            $user->save();

        });

        Log::info('User account updated',['user'=>$user, 'action_by'=>auth()->user()->email]);

        session()->flash('status.user.show',['success'=>'User profile Successfully updated']);

        return redirect()->route('users.show', ['user'=>$user->id]);
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\User  $user
     * @return \Illuminate\Http\Response
     */
    public function destroy(User $user)
    {
        $this->authorize('delete',$user);

        $this->validate(request(),['delete_password'=>'required|verify_user']);

        if($user->isSuperAdmin())
        {
            session()->flash('status.user.delete',['danger'=>'Cannot delete super admin account: '.$user->email]);
            return redirect()->back();
        }

        $user->delete();
        
        Log::info('User account deleted: ',['user'=>$user, 'action_by'=>auth()->user()->email]);
        session()->flash('status.general',['success'=>'Successfully deleted account: '.$user->email]);
        
        return redirect()->route('home');
    }
}

resources/views/users/index.blade.php
@extends('layouts.authenticated')
@section('title')
User Profiles
@endsection
@section('main')
<div class="container">
    <div class="row">
        <div class="col-md">
            <div class="card">
                <div class="card-header">User Profiles</div>

                <div class="card-body">
                    <div class="card-text d-block d-md-none">
                        @component('layouts.components.alert')
                            @slot('type','info')
                            Want to see more info? Just rotate your screen to ladnscape :)
                        @endcomponent
                    </div>
                     <table class="table table-hover">
                         <thead>
                            <tr>
                                <th>Name</th>
                                <th class="d-none d-md-table-cell">Email</th>
                                <th class="d-none d-lg-table-cell">Status</th>
                                <th class="d-none d-lg-table-cell">Created</th>
                                <th class="d-none d-md-table-cell">Actions</th>
                            </tr>
                        </thead>
                     	<tbody>
                     		@forelse($users as $user)
                                <tr>
                                    <td>
                                        <img src="{{$user->avatar}}" class="rounded-circle" height="32" width="32"> &nbsp; <a href="{{ route('users.show',['user'=>$user->id]) }}" title="{{$user->name}}">{{ str_limit($user->name,10) }}</a></td>
                                    <td class="d-none d-md-table-cell">
                                        <a href="mailto:{{$user->email}}" title="{{$user->email}}">{{str_limit($user->email, 10)}}</a>
                                    </td>
                                    <td class="d-none d-lg-table-cell">
                                        <span class="badge @if($user->suspended == true) badge-danger @else badge-success @endif">@if($user->suspended == true) Suspended @else Active @endif</span>&nbsp; <span class="badge @if($user->verified == true) badge-success @else badge-danger @endif">@if($user->verified == true) Verified @else Pending @endif</span>
                                    </td>
                                    <td class="d-none d-lg-table-cell">
                                        {{$user->created_at->diffInDays()>1?$user->created_at->format(config('app.long_date_format')):$user->created_at->diffForHumans()}}
                                    </td>
                                    <td class="d-none d-md-table-cell">
                                        <div class="btn-group">
                                            @if(!$user->isSuperAdmin())
                                                @can('update',$user)
                                                    <a class="btn btn-sm btn-secondary" href="{{route('users.edit',['user'=>$user->id])}}">
                                                        <span class="fas fa-user-edit"></span>
                                                    </a>
                                                @endcan
                                                @can('user_impersonate')
                                                    <a class="btn btn-sm btn-secondary" href="{{route('users.switch',['user'=>$user->id])}}" title="Switch User">
                                                        <span class="fas fa-users"></span>
                                                    </a>
                                                @endcan
                                            @endif
                                        </div>
                                    </td>
                                </tr>
                            @empty
                                <tr>
                                    <td colspan='6' class="text-center">No users</td>
                                </tr>
                            @endforelse
                     	</tbody>
                     </table>
                     <div class="text-center">
                         {{ $users->links() }}
                     </div>
                </div>
                @can('user_stats')
                    <div class="card-footer">
                        [ <a href="{{route('users.stats')}}">Statistics</a> ]
                    </div>
                @endcan
           </div>
        </div>
    </div>
</div>
@endsection
@section('breadcrumbs', Breadcrumbs::render('users.index'))

resources/views/users/show.blade.php
@extends('layouts.authenticated')
@section('title',$user->name)
@section('main')
<div class="container">
    <div class="row">
        <div class="col-md">
            <div class="card">
                <div class="card-header">User Accout Settings</div>
                <div class="card-body">

                     <!-- Let's load the table -->
                     <div class="row">
                        <div class="col-md">
                            @include('layouts.partials.status.custom',['panel'=>'user.show'])
                            <dl class="dl-horizontal">
                                <div class="row mb-3">
                                    <div class="col-md">
                                      <div class="text-center"><img src="{{$user->avatar}}" class="rounded-circle" height="140" width="140">@if($user->avatar)<br><a href="{{route('users.deleteAvatar', ['user'=>$user->id])}}">[ {{__('Delete')}} ]</a>@endif</div>
                                    </div>
                                    <div class="col-md">
                                        <dt>Name</dt>
                                        <dd>{{$user->name}} / {{$user->gender}}</dd>
                                        <dt>{{__('Email')}}</dt>
                                        <dd><a href="mailto:{{$user->email}}" title="{{$user->email}}">{{str_limit($user->email, 20)}}</a></dd>
                                    </div>
                                    <div class="col-md">
                                        <dt>{{__('Created')}}</dt>
                                        <dd>{{$user->created_at->diffInDays()>1?$user->created_at->format(config('app.long_date_format')):$user->created_at->diffForHumans()}}</dd>
                                        <dt>{{__('Last Updated')}}</dt>
                                        <dd>{{$user->updated_at->diffInDays()>1?$user->updated_at->format(config('app.long_date_format')):$user->updated_at->diffForHumans()}}</dd>
                                    </div>
                                </div>
                                <div class="row mb-3" id="pointsApp">
                                    <div class="col-6 col-sm">
                                        <h3><span class="fas fa-coins text-warning">&nbsp;</span> 
                                            <animate-number
                                              from="0" 
                                              to="{{$user->points_in_prediction}}" 
                                              duration="1000" 
                                              easing="easeOutQuad"
                                              :formatter="formatter"
                                            >                                                
                                            </animate-number>
                                        </h3>
                                    </div>
                                    <div class="col-6 col-sm">
                                        <h3><span class="fas fa-coins text-primary">&nbsp;</span> 
                                            <animate-number
                                              from="0" 
                                              to="{{$user->wallet_points}}" 
                                              duration="1000" 
                                              easing="easeOutQuad"
                                              :formatter="formatter"
                                            >                                                
                                            </animate-number>
                                        </h3>
                                    </div>
                                    <div class="col-6 col-sm">
                                        <h3><span class="fas fa-coins text-success">&nbsp;</span> 
                                            <animate-number
                                              from="0" 
                                              to="{{$user->total_points}}" 
                                              duration="1000" 
                                              easing="easeOutQuad"
                                              :formatter="formatter"
                                            >                                                
                                            </animate-number>
                                        </h3>
                                    </div>
                                    <div class="col-6 col-sm">
                                        <h3><span class="fas fa-crown text-warning">&nbsp;</span> 
                                          @if(is_numeric($user->rank))
                                                <animate-number
                                                  from="0" 
                                                  to="{{$user->rank}}" 
                                                  duration="1000" 
                                                  easing="easeOutQuad"
                                                  :formatter="formatter"
                                                >                                                
                                                </animate-number>
                                          @else
                                            {{ucfirst($user->rank)}}
                                          @endif
                                        </h3>
                                    </div>
                                    <div class="col-6 col-sm">
                                        <h3><span class="fas fa-trophy text-warning text-warning">&nbsp;</span> 
                                            <animate-number
                                              from="0" 
                                              to="{{$user->total_wins}}" 
                                              duration="1000" 
                                              easing="easeOutQuad"
                                              :formatter="formatter"
                                            >                                                
                                            </animate-number>
                                        </h3>
                                    </div>
                                </div>
                            </dl>
                            @can('user_update_profile')
                                <fieldset><legend>{{__('Admin')}}</legend>
                                    <dl class="dl-horizontal">
                                        <dt>{{__('Status')}}</dt>
                                        <dd><span class="badge @if($user->suspended == true) badge-danger @else badge-success @endif">@if($user->suspended == true) {{__('Suspended')}} @else {{__('Active')}} @endif</span>&nbsp; <span class="badge @if($user->verified == true) badge-success @else badge-danger @endif">@if($user->verified == true) {{__('Verified')}} @else {{__('Pending')}} @endif</span></dd>
                                    </dl>
                                </fieldset>
                                @if($user->roles->count())
                                    <fieldset><legend>{{__('Roles')}}</legend>
                                        <ul>
                                        @foreach($user->roles as $role)
                                            <li>{{$role->label}}</li>
                                        @endforeach
                                        </ul>
                                    </fieldset>
                                @endif
                            @endcan
                        </div>
                    </div>
                </div>
                <div class="card-footer">
                    @can('update',$user)
                        <a href="{{route('users.edit', ['user'=>$user->id])}}">[ Update ]</a> 
                    @endcan
                    @can('show', App\Point::class)
                        <a href="{{route('users.points.index', ['user'=>$user->id])}}">[ <span class="fas fa-coins"></span> Points History ]</a> 
                    @endcan
                    @can('user_impersonate')
                      <a href="{{route('users.switch',['user'=>$user->id])}}">[ Switch User ]</a>
                    @endcan
                </div>
           </div>
        </div>
    </div>
</div>
@endsection

@section('breadcrumbs', Breadcrumbs::render('users.show', $user))