routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

// Route::get('/', function () {
//     return view('welcome');
// })->name('welcome');

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');
Route::get('/', 'HomeController@welcome')->name('welcome');

// start role routes
Route::resource('/roles','RoleController');
Route::view('/rules','rules')->name('rules');
// end role routes

// start user routes
Route::get('/users/stop','UserController@origUser')->name('users.orig');
Route::get('/users/stats','UserController@stats')->name('users.stats');
Route::get('/users/list','UserController@list')->name('users.list');
Route::resource('/users','UserController',['except'=>['create']]);

Route::group(['prefix'=>'users/{user}/', 'as'=>'users.'], function() {
	Route::get('verify/{email_key}', 'Auth\RegisterController@verifyUser')->name('verify');
	Route::resource('points','PointController', ['only'=>['index']]);
	Route::group(['prefix'=>'points', 'as'=>'points.'], function(){
		Route::get('buy','PointController@buyForm')->name('buy.form');
		Route::post('buy','PointController@buyStore')->name('buy');
	});
});

Route::group(['prefix'=>'points','as'=>'points.'], function() {
	Route::get('bulkAdd','PointController@bulkAdd')->name('bulkAdd');
	Route::post('bulkAdd','PointController@bulkStore')->name('bulkStore');
});

// end user routes

// switch user
Route::get('/users/{user}/switch','UserController@switchUser')->name('users.switch')->middleware('can:switchUser,App\User');
// end switch user

Route::post('/invitations/{invitation}/resend', 'InvitationController@resend')->name('invitations.resend');
Route::resource('/invitations','InvitationController');

Route::get('/teams/list', 'TeamController@list')->name('teams.list');
Route::resource('/teams', 'TeamController');
Route::resource('/games', 'GameController');
Route::get('/games/generate/{group}', 'GameController@generate')->name('games.generate');

Route::group(['prefix'=>'games/{game}', 'as'=>'games.'], function() {
	Route::resource('predictions', 'PredictionController');	
	Route::get('result', 'GameController@getResults')->name('result');	
	Route::put('result', 'GameController@saveResults')->name('result.save');	
});

Route::get('leaderboard','RankController@leaderboard')->name('leaderboard');

Route::get('/users/{user}/deleteAvatar', 'UserController@deleteAvatar')->name('users.deleteAvatar');

Route::resource('/feedback','FeedbackController',['only'=>['store','index']]);

resources/views/layouts/partials/sidebar.blade.php
<div class="container">
    <div class="row">
        <div class="col-lg">
            <div class="card">
                <div class="navbar navbar-expand-lg navbar-light navbar-laravel  pl-0 pr-0">
                    <div class="container pl-0 pr-0">
                        <div class="card-heading ml-2">
                            <button class="navbar-toggler ml-2" type="button" data-toggle="collapse" data-target="#sidebarNav" aria-controls="sidebarNav" aria-expanded="false" aria-label="Toggle navigation">
                                <span class="navbar-toggler-icon"></span>
                            </button>
                        </div>
                        <div class="collapse navbar-collapse" id="sidebarNav">
                            <div class="card-body">
                                <h5 class="card-title">Navigation</h5>
                                <p class="card-text">
                                    <div class="list-group list-group-flush"> 
                                        @if(auth::check())
                                            <a class="list-group-item list-group-item-action @if(str_is('home',Route::getCurrentRoute()->uri)) active @endif" href="{{route('home')}}"><span class="fas fa-home">&nbsp;</span>Dashboard</a>

                                            <a class="list-group-item list-group-item-action @if(str_is('users/{user}',Route::getCurrentRoute()->uri)) active @endif" href="{{route('users.show', ['user'=> auth::user()->id])}}"><span class="fas fa-user-circle">&nbsp;</span>My Profile</a>

                                            <a class="list-group-item list-group-item-action @if(str_is('users/{user}*/points',Route::getCurrentRoute()->uri)) active @endif" href="{{route('users.points.index', ['user'=> auth::user()->id])}}"><span class="fas fa-coins text-warning">&nbsp;</span>Points <span class="badge badge-warning">{{number_format(auth::user()->wallet_points)}}</span></a>

                                            @can('exchange', App\Point::class)
                                                <a class="list-group-item list-group-item-action @if(str_is('users/{user}*/points/buy',Route::getCurrentRoute()->uri)) active @endif" href="{{route('users.points.buy.form', ['user'=> auth::user()->id])}}"><i class="fas fa-exchange-alt"></i> Get more points</a>
                                            @endcan                                            
                                        @endif

                                        @can('view',App\Game::class)
                                            <a class="list-group-item list-group-item-action @if(strpos(Route::getCurrentRoute()->uri,'games')!==false) active @endif" href='{{route("games.index")}}'><span class="fas fa-futbol">&nbsp;</span>Games</a>
                                        @endcan
                                        
                                        <a class="list-group-item list-group-item-action @if(strpos(Route::getCurrentRoute()->uri,'leaderboard')!==false) active @endif" href='{{route("leaderboard")}}'><span class="fas fa-trophy">&nbsp;</span>Leaderboard</a>

                                        @can('user_view')
                                            <a class="list-group-item list-group-item-action @if(str_is('users*',Route::getCurrentRoute()->uri)!==false) active @endif" href='{{route("users.index")}}'><span class="fas fa-users">&nbsp;</span>Users</a>
                                        @endcan

                                        @can('permission_view')
                                            <a class="list-group-item list-group-item-action @if(strpos(Route::getCurrentRoute()->uri,'roles')!==false) active @endif" href='{{route("roles.index")}}'><span class="fab fa-keycdn">&nbsp;</span>Roles</a>
                                        @endcan

                                        @can('invitation_create')
                                            <a class="list-group-item list-group-item-action @if(strpos(Route::getCurrentRoute()->uri,'invitations')!==false) active @endif" href='{{route("invitations.index")}}'><span class="fas fa-key">&nbsp;</span>Invitations</a>
                                        @endcan

                                        @can('team_view')
                                            <a class="list-group-item list-group-item-action @if(strpos(Route::getCurrentRoute()->uri,'teams')!==false) active @endif" href='{{route("teams.index")}}'><span class="fas fa-flag">&nbsp;</span>Teams</a>
                                        @endcan

                                        @can('add', App\Point::class)
                                            <a class="text-danger list-group-item list-group-item-action @if(str_is('points/bulkAdd',Route::getCurrentRoute()->uri)) active @endif" href="{{route('points.bulkAdd')}}"><span class="fas fa-coins">&nbsp;</span>Add Points</a>
                                        @endcan
                                        @if(config('app.feedback.typeform')!==false)
                                            <a class="list-group-item list-group-item-action @if(str_is('feedback',Route::getCurrentRoute()->uri)) active @endif" href="{{route('feedback.index')}}"><i class="fas fa-comments">&nbsp;</i>Feedback</a>
                                        @endif

                                        <a target="__blank" class="list-group-item list-group-item-action @if(strpos(Route::getCurrentRoute()->uri,'rules')!==false) active @endif" href='{{route("rules")}}'><span class="fas fa-hand-point-right">&nbsp;</span>Rules</a>
                                    </div>
                                </p>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>