routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

// Route::get('/', function () {
//     return view('welcome');
// })->name('welcome');

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');
Route::get('/', 'HomeController@welcome')->name('welcome');

// start role routes
Route::resource('/roles','RoleController');
Route::view('/rules','rules')->name('rules');
// end role routes

// start user routes
Route::get('/users/stop','UserController@origUser')->name('users.orig');
Route::get('/users/stats','UserController@stats')->name('users.stats');
Route::get('/users/list','UserController@list')->name('users.list');
Route::resource('/users','UserController',['except'=>['create']]);

Route::group(['prefix'=>'users/{user}/', 'as'=>'users.'], function() {
	Route::get('verify/{email_key}', 'Auth\RegisterController@verifyUser')->name('verify');
	Route::resource('points','PointController', ['only'=>['index']]);
	Route::group(['prefix'=>'points', 'as'=>'points.'], function(){
		Route::get('buy','PointController@buyForm')->name('buy.form');
		Route::post('buy','PointController@buyStore')->name('buy');
	});
});

Route::group(['prefix'=>'points','as'=>'points.'], function() {
	Route::get('bulkAdd','PointController@bulkAdd')->name('bulkAdd');
	Route::post('bulkAdd','PointController@bulkStore')->name('bulkStore');
});

// end user routes

// switch user
Route::get('/users/{user}/switch','UserController@switchUser')->name('users.switch')->middleware('can:switchUser,App\User');
// end switch user

Route::post('/invitations/{invitation}/resend', 'InvitationController@resend')->name('invitations.resend');
Route::resource('/invitations','InvitationController');

Route::get('/teams/list', 'TeamController@list')->name('teams.list');
Route::resource('/teams', 'TeamController');
Route::resource('/games', 'GameController');
Route::get('/games/generate/{group}', 'GameController@generate')->name('games.generate');

Route::group(['prefix'=>'games/{game}', 'as'=>'games.'], function() {
	Route::resource('predictions', 'PredictionController');	
	Route::get('result', 'GameController@getResults')->name('result');	
	Route::put('result', 'GameController@saveResults')->name('result.save');	
});

Route::get('leaderboard','RankController@leaderboard')->name('leaderboard');

Route::get('/users/{user}/deleteAvatar', 'UserController@deleteAvatar')->name('users.deleteAvatar');

Route::resource('/feedback','FeedbackController',['only'=>['store','index']]);

app/Invitation.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Notifications\Notifiable;

class Invitation extends Model
{
    use Notifiable;
    
    protected $fillable = ['email'];
    protected $hidden = ['invitation_code'];
	
	public $incrementing = false;
    protected $primaryKey = 'email';
    
    public function setInvitationCodeAttribute($value)
    {
    	$this->attributes['invitation_code'] = encrypt($value);
    }

    public function getInvitationCodeAttribute()
    {
    	return decrypt($this->attributes['invitation_code']);
    }

    public function save(array $options = [])
    {
        $this->invitation_code = str_random(25);
        return parent::save($options);
    }

    public function isValid($code)
    {
    	return $code === $this->invitation_code;
    }
}

app/Http/Controllers/InvitationController.php
<?php

namespace App\Http\Controllers;

use App\Invitation;
use App\Rules\IsAccentureEmail;
use Illuminate\Http\Request;

use App\Notifications\SendInvitations;

use Log;

class InvitationController extends Controller
{
    public function __construct()
    {
        $this->middleware('can:invitation_create');
    }

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $invitations = Invitation::latest()->paginate(config('app.page_size'));
        return view('invitations.index',compact('invitations'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('invitations.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $this->validate($request, ['email.*' => ['nullable'
                                                , 'distinct'
                                                , 'string'
                                                , 'email'
                                                , 'max:255'
                                                , 'unique:users,email'
                                                , 'unique:invitations,email'
                                                , new IsAccentureEmail()]]);
        
        $numInvites = 0;

        foreach ($request->email as $email) {
            if(strlen($email) > 0)
            {
                $numInvites++;
                $invitation = Invitation::create(['email'=>$email]);
                $invitation->notify(new SendInvitations($invitation));
                Log::info('Invitation generated',['invitation_for'=>$invitation->email, 'action_by'=>auth()->user()]);
            }
        }


        return redirect()->route('invitations.index')->with('status.invitations.index',['success'=>$numInvites.' '.str_plural('invitation',$numInvites).' successfully generated']);

    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Invitation  $invitation
     * @return \Illuminate\Http\Response
     */
    public function destroy(Invitation $invitation)
    {
        $invitation->delete();
        Log::info('Invitation deleted',['invitation_for'=>$invitation->email, 'action_by'=>auth()->user()]);
        return redirect()->route('invitations.index')->with('status.invitations.index',['success'=>'Invitation for '.$invitation->email.' successfully deleted']);
    }

    public function resend(Invitation $invitation)
    {
        $invitation->notify(new SendInvitations($invitation));

        return redirect()->route('invitations.index')->with('status.invitations.index',['success'=>'Invitation resend to '.$invitation->email.' successfully']);
    }
}

resources/views/invitations/create.blade.php
@extends('layouts.authenticated')
@section('title')
Add Invitations
@endsection
@section('main')

    <div class="row">
        <div class="col-md-12">
            <div class="card mb-3">
                <div class="card-header">Add Invitations</div>
                <div class="card-body">
                    @include('layouts.partials.status.custom',['panel'=>'invitations.create'])
                    @if ($errors->any())
                        <div class="alert alert-danger">
                            There are errors in your submission. Please clear them.
                        </div>
                    @endif
                    <form  id='invitesApp' class="form-horizontal" method="POST" action="{{ route('invitations.index') }}">
                        @csrf
                        <p class="text-muted">If it is just a few email IDs, you can enter the ID in the below text box. As and when you enter it, a new text box will appear for you to enter the next one.</p>
                        <div class="form-group row" v-for="(email, index) in emails">
                            <label for="email" class="col-md-4 col-form-label text-md-right">Email @{{index+1}}</label>

                            <div class="col-md-6">
                                <input type="text" class="form-control" v-bind:class="{ 'is-invalid': email.hasError }" name="email[]" v-model="email.email" autofocus placeholder="@if(config('app.fifa.domain_restriction') !== false)Any {{'@'.config('app.fifa.domain_restriction')}} email ID @else Any email ID @endif"  @keyup.prevent="newEmail()">
                                    <span class="invalid-feedback">
                                        <strong>@{{ email.error }}</strong>
                                    </span>
                            </div>
                        </div>
                        <p class="text-muted">Alternatively, if the list is huge, you may choose a plain text file with one email ID per line.</p>

                        <div class="form-group row">
                            <label for="email" class="col-md-4 col-form-label text-md-right">Bulk Upload</label>

                            <div class="col-md-6">
                                <div class="custom-file form-control" v-bind:class="{ 'is-invalid': fileError }">
                                    <input type="file" class="custom-file-input" id="customFile" ref="customFile" @change.prevent="bulkLoad()">
                                    <label class="custom-file-label" for="customFile">Choose a plain text file</label>
                                </div>
                                <span class="form-text text-muted">
                                    Upload a plain text file with one email ID per line
                                </span>
                                <span class="invalid-feedback">
                                    <strong>@{{ fileErrorMessage }}</strong>
                                </span>
                            </div>
                        </div>

                        <div class="form-group row">
                            <div class="col-md-8 offset-md-4">
                                <button type="submit" class="btn btn-primary">
                                    Invite
                                </button>
                            </div>
                        </div>
                    </form>
                </div>
           </div>
        </div>
    </div>

@endsection

@section('breadcrumbs', Breadcrumbs::render('invitations.create'))
@push('bottomJs')
    <script type="text/javascript">
        Vue.config.devtools = true;
        const invitesApp = new Vue({
            el: '#invitesApp'
            , data: {
                emails: [
                    @if(null !== old('email'))
                        @foreach(old('email') as $e)
                            {
                                email: "{{null !== old('email.'.$loop->index) ? old('email.'.$loop->index) : ''}}"
                                , hasError: {{$errors->has('email.'.$loop->index) ? 'true' : 'false'}}
                                , error: "{{$errors->first('email.'.$loop->index)}}"
                            }
                            @if(!$loop->last)
                                ,
                            @endif
                        @endforeach
                     @else
                        {
                            email: ''
                            , hasError: false
                            , error: ''
                        }
                    @endif
                        ]
                , fileError: false
                , fileErrorMessage: ''
            }
            , methods: {
                newEmail: function() {
                    needNew = true;
                    this.emails.forEach((email) => {
                        if(email.email.length == 0) needNew=false;
                    });

                    if(needNew)
                    {
                        this.emails.push({email: ''});
                    }
                }
                , bulkLoad: function() {
                     //Set the extension for the file 
                     var fileExtension = /text.*/; 
                     //Get the file object 
                     var fileTobeRead = this.$refs.customFile.files[0];
                    //Check of the extension match 
                     if (fileTobeRead.type.match(fileExtension)) 
                     { 
                         invitesApp.fileErrorMessage = '';
                         invitesApp.fileError = false;
                         //Initialize the FileReader object to read the 2file 
                         var fileReader = new FileReader(); 
                         fileReader.onload = function (e) 
                         { 
                             invitesApp.emails.pop();
                             emails = fileReader.result.split("\n");
                             $.each(emails, function(index){
                                invitesApp.emails.push({email: emails[index]});
                             });
                         } 
                         fileReader.readAsText(fileTobeRead); 
                     } 
                     else 
                     { 
                         invitesApp.fileError = true; 
                         invitesApp.fileErrorMessage = 'You can use only a plain text file.'
                     }
                }
            }
        });
    </script>
@endpush

resources/views/invitations/index.blade.php
@extends('layouts.authenticated')
@section('title')
Manage Invitations
@endsection
@section('main')
<div class="container">
    <div class="row">
        <div class="col-md">
            <div class="card">
                <div class="card-header">Manage Invitations</div>

                <div class="card-body">
                     @include('layouts.partials.status.custom',['panel'=>'invitations.index'])


                     <!-- Let's load the table -->
                     <table class="table table-hover">
                         <thead>
                            <tr>
                                <th>Email</th>
                                <th class="d-none d-md-table-cell">Invitation Code</th>
                                <th class="d-none d-lg-table-cell">Created</th>
                                <th class="hidden-xs">Actions</th>
                            </tr>
                        </thead>
                     	<tbody>
                     		@forelse($invitations as $invite)
                                <tr>
                                    <td title="{{$invite->email}}">{{str_limit($invite->email, 20)}}</td>
                                    <td class="d-none d-md-table-cell">{{$invite->invitation_code}}</td>
                                    <td class="d-none d-lg-table-cell">{{$invite->created_at->diffInDays()>1?$invite->created_at->format(config('app.long_date_format')):$invite->created_at->diffForHumans()}}</td>
                                    <td class="hidden-xs">
                                        <form id="delete-resend-{{$invite->invitation_code}}" action="{{ route('invitations.resend',['invite'=>$invite->email]) }}" method="POST" style="display:none;">
                                            @csrf
                                            {{ method_field('POST') }}
                                        </form>
                                        <form id="delete-invite-{{$invite->invitation_code}}" action="{{ route('invitations.destroy',['invite'=>$invite->email]) }}" method="POST" style="display:none;">
                                            @csrf
                                            {{ method_field('DELETE') }}
                                        </form>
                                        <div class="btn-group">
                                            <a class="btn btn-sm btn-secondary" href="{{ route('invitations.resend',['invite'=>$invite->email]) }}" onclick="event.preventDefault(); $('#delete-resend-{{$invite->invitation_code}}').submit();">
                                                <span class="fas fa-envelope"></span>
                                            </a>
                                            <a class="btn btn-sm btn-danger" href="{{ route('invitations.destroy',['invite'=>$invite->email]) }}" onclick="event.preventDefault(); $('#delete-invite-{{$invite->invitation_code}}').submit();">
                                                <span class="fas fa-trash-alt"></span>
                                            </a>
                                        </div>
                                    </td>
                                </tr>
                            @empty
                                <tr>
                                    <td colspan='6' class="text-center">No Invitations Found</td>
                                </tr>
                            @endforelse
                     	</tbody>
                     </table>
                     <div class="text-center">
                         {{ $invitations->links() }}
                     </div>
                </div>
                <div class="card-footer">
                    <a href="{{route('invitations.create')}}">Invite People</a>
                </div>
           </div>
        </div>
    </div>
</div>
@endsection
@section('breadcrumbs', Breadcrumbs::render('invitations.index'))