routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

// Route::get('/', function () {
//     return view('welcome');
// })->name('welcome');

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');
Route::get('/', 'HomeController@welcome')->name('welcome');

// start role routes
Route::resource('/roles','RoleController');
Route::view('/rules','rules')->name('rules');
// end role routes

// start user routes
Route::get('/users/stop','UserController@origUser')->name('users.orig');
Route::get('/users/stats','UserController@stats')->name('users.stats');
Route::get('/users/list','UserController@list')->name('users.list');
Route::resource('/users','UserController',['except'=>['create']]);

Route::group(['prefix'=>'users/{user}/', 'as'=>'users.'], function() {
	Route::get('verify/{email_key}', 'Auth\RegisterController@verifyUser')->name('verify');
	Route::resource('points','PointController', ['only'=>['index']]);
	Route::group(['prefix'=>'points', 'as'=>'points.'], function(){
		Route::get('buy','PointController@buyForm')->name('buy.form');
		Route::post('buy','PointController@buyStore')->name('buy');
	});
});

Route::group(['prefix'=>'points','as'=>'points.'], function() {
	Route::get('bulkAdd','PointController@bulkAdd')->name('bulkAdd');
	Route::post('bulkAdd','PointController@bulkStore')->name('bulkStore');
});

// end user routes

// switch user
Route::get('/users/{user}/switch','UserController@switchUser')->name('users.switch')->middleware('can:switchUser,App\User');
// end switch user

Route::post('/invitations/{invitation}/resend', 'InvitationController@resend')->name('invitations.resend');
Route::resource('/invitations','InvitationController');

Route::get('/teams/list', 'TeamController@list')->name('teams.list');
Route::resource('/teams', 'TeamController');
Route::resource('/games', 'GameController');
Route::get('/games/generate/{group}', 'GameController@generate')->name('games.generate');

Route::group(['prefix'=>'games/{game}', 'as'=>'games.'], function() {
	Route::resource('predictions', 'PredictionController');	
	Route::get('result', 'GameController@getResults')->name('result');	
	Route::put('result', 'GameController@saveResults')->name('result.save');	
});

Route::get('leaderboard','RankController@leaderboard')->name('leaderboard');

Route::get('/users/{user}/deleteAvatar', 'UserController@deleteAvatar')->name('users.deleteAvatar');

Route::resource('/feedback','FeedbackController',['only'=>['store','index']]);

app/Role.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Role extends Model
{
    protected $fillable=['name','label'];

    public function permissions()
    {
    	return $this->belongsToMany(Permission::class);
    }

    public function givePermission($permission)
    {
        if($permission)
            $permission = is_array($permission)?$permission:[$permission->id];
    	
    	return $this->permissions()->sync($permission);
    }

    public function addPermission($permission)
    {
        return $this->permissions()->attach($permission);
    }

    public function users()
    {
    	return $this->belongsToMany(User::class);
    }

    public function setNameAttribute($value)
    {
        $this->attributes['name'] = strtolower($value);
    }

    public function getNameAttribute($value)
    {
        return strtolower($value);
    }

    public function getRouteKeyName()
    {
        return 'name';
    }

}

app/Http/Controllers/RoleController.php
<?php

namespace App\Http\Controllers;

use App\Role;
use App\Permission;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Log;

class RoleController extends Controller
{
    public function __construct()
    {
        $this->middleware('can:permission_view');
    }

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index(Role $role)
    {
        $roles = $role->paginate(config('app.page_size'));
        return view('roles.index',compact('roles'));
    }

    public function show(Role $role)
    {
        $role = Role::with('permissions')->findorfail($role)->first();
        return view('roles.show',compact('role'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $this->authorize('role_manage');

        $permissions = Permission::orderBy('name')->get();

        return view('roles.create',compact('permissions'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $this->authorize('role_manage');

        $this->validate($request, ['name'=>'required|alpha_dash|unique:roles,name'
                                    ,'label'=>'string|nullable'
                                    ,'permissions'=>'array|exists:permissions,id']);

        $role = Role::create(request(['name','label']));

        $role->givePermission($request->permissions);

        session()->flash('status.roles.show',['success'=>__(':Type :data Successfully created', ['Type'=>__('Role'),'data'=>$role->name])]);

        return redirect()->route('roles.show',['role'=>$role->name]);
    }


    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Role  $role
     * @return \Illuminate\Http\Response
     */
    public function edit(Role $role)
    {
        $this->authorize('role_manage');

        $role = Role::with('permissions')->findorfail($role)->first();
        
        $permissions = Permission::orderBy('name')->get();

        return view('roles.edit',compact('role','permissions'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Role  $role
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Role $role)
    {
        $this->authorize('role_manage');

        $this->validate($request, ['name'=>'required|alpha_dash'
                                    ,'label'=>'string|nullable'
                                    ,'permissions'=>'array|exists:permissions,id']);

        $role->givePermission($request->permissions);

        $role->fill(request(['name','label']));
        $role->Save();

        session()->flash('status.roles.show',['success'=>__(':Type :data Successfully updated', ['Type'=>__('Role'),'data'=>$role->name])]);

        return redirect()->route('roles.show',['role'=>$role->name]);
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Role  $role
     * @return \Illuminate\Http\Response
     */
    public function destroy(Role $role)
    {
        $this->authorize('role_manage');

        if($role->id==1)
            abort(403,'Cannot delete customer role');

        $role->delete();

        Log::info('Role deleted.',['role'=>$role]);
        session()->flash('status.roles.index',['success'=>__(':Type :data Successfully deleted', ['Type'=>__('Role'),'data'=>$role->name])]);
        return redirect()->route('roles.index');
    }
}

resources/views/roles/create.blade.php
@extends('layouts.authenticated')
@section('title')
Add Role
@endsection
@section('main')

    <div class="row">
        <div class="col-md-12">
            <div class="card mb-3">
                <div class="card-header">Add Role</div>
                <div class="card-body">
                    @include('layouts.partials.status.custom',['panel'=>'roles.create'])
                    <form class="form-horizontal" method="POST" action="{{ route('roles.index') }}">
                        @csrf

                        <div class="form-group row">
                            <label for="name" class="col-md-4 col-form-label text-md-right">Name</label>

                            <div class="col-md-6">
                                <input id="name" type="text" class="form-control{{ $errors->has('name') ? ' is-invalid' : '' }}" name="name" value="{{ old('name') }}"  autofocus placeholder="sales_manager" required>
                                @if ($errors->has('name'))
                                    <span class="invalid-feedback">
                                        <strong>{{ $errors->first('name') }}</strong>
                                    </span>
                                @endif
                            </div>
                        </div>

                        <div class="form-group row">
                            <label for="label" class="col-md-4 col-form-label text-md-right">Description</label>

                            <div class="col-md-6">
                                <input id="label" type="text" class="form-control{{ $errors->has('label') ? ' is-invalid' : '' }}" name="label" value="{{ old('label') }}" placeholder="Manage close sales">
                                @if ($errors->has('label'))
                                    <span class="invalid-feedback">
                                        <strong>{{ $errors->first('label') }}</strong>
                                    </span>
                                @endif
                            </div>
                        </div>

                        <fieldset>
                            <legend>Roles</legend>
                                <div class="form-group row">
                                    <div class="offset-4 col-md col-form-label text-md-justify">
                                        @foreach($permissions as $permission)
                                            <div class="checkbox">
                                                <label>
                                                    <input type="checkbox" name="permissions[]" value="{{$permission->id}}"> {{$permission->label}} ({{$permission->name}})
                                                </label>
                                            </div>
                                        @endforeach
                                    </div>
                                </div>
                        </fieldset>

                        <div class="form-group row">
                            <div class="col-md-8 offset-md-4">
                                <button type="submit" class="btn btn-primary">
                                    Add Role
                                </button>
                            </div>
                        </div>
                    </form>
                </div>
           </div>
        </div>
    </div>

@endsection

@section('breadcrumbs', Breadcrumbs::render('roles.create'))

resources/views/roles/edit.blade.php
@extends('layouts.authenticated')
@section('title')
Edit Role {{$role->label}}
@endsection
@section('main')

    <div class="row">
        <div class="col-md">
            <div class="card mb-3">
                <div class="card-header">Edit Role {{$role->label}}</div>

                <div class="card-body">
                     <form class="form-horizontal" method="POST" action="{{ route('roles.update',['role'=>$role->name]) }}">
                        @csrf
                        {{ method_field('PUT') }}

                        <div class="form-group row">
                            <label for="name" class="col-md-4 col-form-label text-md-right">Name</label>

                            <div class="col-md-6">
                                <input id="name" type="text" class="form-control{{ $errors->has('name') ? ' is-invalid' : '' }}" name="name" value="{{ old('name')?:$role->name }}"  autofocus placeholder="sales_manager" required>
                                @if ($errors->has('name'))
                                    <span class="invalid-feedback">
                                        <strong>{{ $errors->first('name') }}</strong>
                                    </span>
                                @endif
                            </div>
                        </div>

                        <div class="form-group row">
                            <label for="label" class="col-md-4 col-form-label text-md-right">Description</label>

                            <div class="col-md-6">
                                <input id="label" type="text" class="form-control{{ $errors->has('label') ? ' is-invalid' : '' }}" name="label" value="{{ old('label')?:$role->label }}" placeholder="Manage close sales">
                                @if ($errors->has('label'))
                                    <span class="invalid-feedback">
                                        <strong>{{ $errors->first('label') }}</strong>
                                    </span>
                                @endif
                            </div>
                        </div>

                        <fieldset>
                            <legend>{{__('Roles')}}</legend>
                                <div class="form-group row">
                                    <div class="offset-4 col-md col-form-label text-md-justify">
                                        @foreach($permissions as $permission)
                                            <div class="checkbox">
                                                <label>
                                                    <input type="checkbox" name="permissions[]" value="{{$permission->id}}" @if($role->permissions->contains('id',$permission->id)) checked @endif> {{$permission->label}} ({{$permission->name}})
                                                </label>
                                            </div>
                                        @endforeach
                                    </div>
                                </div>
                        </fieldset>

                        <div class="form-group row">
                            <div class="col-md-8 offset-md-4">
                                <button type="submit" class="btn btn-primary">
                                   Update Role
                                </button>
                            </div>
                        </div>
                    </form>
                </div>
           </div>
        </div>
    </div>

@endsection

@section('breadcrumbs', Breadcrumbs::render('roles.edit',$role))

resources/views/roles/index.blade.php
@extends('layouts.authenticated')
@section('title')
Manage Roles
@endsection
@section('main')
<div class="container">
    <div class="row">
        <div class="col-md">
            <div class="card">
                <div class="card-header">Manage Roles</div>

                <div class="card-body">
                     @include('layouts.partials.status.custom',['panel'=>'roles.index'])

                     <table class="table table-hover">
                        <thead>
                            <tr>
                                <th class="d-table-cell d-none">Name</th>
                                <th class="d-none d-sm-table-cell">Label</th>
                                <th>Actions</th>
                            </tr>
                        </thead>
                        <tbody>
                            @foreach($roles as $role)
                            <tr>
                                <td class="d-table-cell d-none">{{ $role->name }}</a></td>
                                <td class="d-none d-sm-table-cell">{{ $role->label }}</a></td>
                                <td>
                                    <div class="btn-group">
                                        @can('permission_view')
                                            <a class="btn btn-sm btn-secondary" href="{{ route('roles.show',['role'=>$role->name]) }}">
                                                <span class="fas fa-eye"></span>
                                            </a>
                                        @endcan
                                        @can('role_manage')
                                            <a class="btn btn-sm btn-secondary" href="{{ route('roles.edit',['role'=>$role->name]) }}">
                                                <span class="fas fa-user-edit"></span>
                                            </a>
                                            @if($role->id > 2)
                                                <form id="delete-role-{{$role->id}}" action="{{ route('roles.destroy',['role'=>$role->name]) }}" method="POST" style="display:none;">
                                                    @csrf
                                                    {{ method_field('DELETE') }}
                                                </form>
                                                <a class="btn btn-sm btn-danger" href="{{ route('roles.destroy',['role'=>$role->name]) }}" onclick="event.preventDefault(); $('#delete-role-{{$role->id}}').submit();">
                                                    <span class="fas fa-trash-alt"></span>
                                                </a>
                                            @endif
                                        @endcan
                                    </div>
                                </td>
                            </tr>
                            @endforeach
                        </tbody>
                    </table>
                    <div class="text-center">{{ $roles->links() }}</div>
                </div>
                @can('role_manage')
                    <div class="card-footer">
                        <a href="{{route('roles.create')}}">Add Role</a>
                    </div>
                @endcan
           </div>
        </div>
    </div>
</div>
@endsection
@section('breadcrumbs', Breadcrumbs::render('roles.index'))

resources/views/roles/show.blade.php
@extends('layouts.authenticated')
@section('title')
Role details - {{$role->label}}
@endsection
@section('main')

    <div class="row">
        <div class="col-md-12">
            <div class="card mb-3">
                <div class="card-header">Role details - {{$role->label}}</div>
                <div class="card-body">
                    @include('layouts.partials.status.custom',['panel'=>'roles.show'])
                    <div class="row">
                        <div class="col-md-6">
                            <dl class="dl-horizontal">
                                <dt>Name</dt>
                                <dd>{{ $role->name }}</dd>
                                <dt>Description</dt>
                                <dd>{{$role->label}}</dd>
                            </dl>
                        </div>
                        <div class="col-md-6">
                            <dl class="dl-horizontal">
                                <dt>Created</dt>
                                <dd>{{$role->created_at->diffInDays()>1?$role->created_at->format(config('app.long_date_format')):$role->created_at->diffForHumans()}}</dd>
                                <dt>Last Updated</dt>
                                <dd>{{$role->updated_at->diffInDays()>1?$role->updated_at->format(config('app.long_date_format')):$role->updated_at->diffForHumans()}}</dd>
                            </dl>
                        </div>
                    </div>
                </div>
                @can('role_manage')
                    <div class="card-footer">
                        [ <a href="{{route('roles.edit',['role'=>$role->name])}}">Edit Role / Modify Associated Permissions</a> ] 
                    </div>
                @endcan
           </div>
           <div class="card mb-3">
               <div class="card-header">Associated Permissions</div>
               <div class="card-body">
                   <div class="row">
                        <div class="col-md-12">
                            <table class="table table-hover">
                                <thead>
                                    <tr>
                                        <th>Name</th>
                                        <th>Description</th>
                                    </tr>
                                </thead>
                                <tbody>
                                    @forelse($role->permissions as $permission)
                                        <tr>
                                            <td>{{$permission->name}}</td>
                                            <td>{{$permission->label}}</td>
                                        </tr>
                                    @empty
                                        <tr>
                                            <td colspan="2" class="text-muted text-center">No permissions assigned</td>
                                        </tr>
                                    @endforelse
                                </tbody>
                            </table>
                        </div>
                    </div>
               </div>
           </div>
        </div>
    </div>
@endsection
@section('breadcrumbs', Breadcrumbs::render('roles.show',$role))